apiVersion: v1

kind: Pod

metadata:

  labels:

    test: liveness

  name: online-inference-pod-probes

spec:
  containers:
  - name: mlp
    image: krastykovyaz/ft_perceptron-app:0.0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 65
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 60

